#!/bin/zsh
set -euo pipefail

WORKDIR="/Users/emre/Dergah"

usage() {
  echo "Kullanim: scripts/join_mac_node.sh --role worker1|worker2 --m5-host HOST --github-owner OWNER --github-repo REPO --github-issue ISSUE [secenekler]"
  echo "Secenekler:"
  echo "  --node-name NAME"
  echo "  --github-token TOKEN"
  echo "  --model MODEL"
  echo "  --provider openai_compat|ollama"
  echo "  --coordinator-url URL"
  echo "  --start-relay"
  echo "  --start-openclaw"
  echo "  --start-status"
  exit 1
}

ROLE=""
NODE_NAME=""
M5_HOST=""
GITHUB_OWNER=""
GITHUB_REPO=""
GITHUB_ISSUE=""
GITHUB_TOKEN="${DERGAH_GITHUB_TOKEN:-}"
MODEL_NAME="qwen2.5:32b"
PROVIDER="openai_compat"
COORDINATOR_URL=""
START_RELAY="0"
START_OPENCLAW="0"
START_STATUS="0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --role)
      ROLE="${2:-}"
      shift 2
      ;;
    --node-name)
      NODE_NAME="${2:-}"
      shift 2
      ;;
    --m5-host)
      M5_HOST="${2:-}"
      shift 2
      ;;
    --github-owner)
      GITHUB_OWNER="${2:-}"
      shift 2
      ;;
    --github-repo)
      GITHUB_REPO="${2:-}"
      shift 2
      ;;
    --github-issue)
      GITHUB_ISSUE="${2:-}"
      shift 2
      ;;
    --github-token)
      GITHUB_TOKEN="${2:-}"
      shift 2
      ;;
    --model)
      MODEL_NAME="${2:-}"
      shift 2
      ;;
    --provider)
      PROVIDER="${2:-}"
      shift 2
      ;;
    --coordinator-url)
      COORDINATOR_URL="${2:-}"
      shift 2
      ;;
    --start-relay)
      START_RELAY="1"
      shift
      ;;
    --start-openclaw)
      START_OPENCLAW="1"
      shift
      ;;
    --start-status)
      START_STATUS="1"
      shift
      ;;
    *)
      echo "Bilinmeyen arguman: $1"
      usage
      ;;
  esac
done

[[ -n "$ROLE" && -n "$M5_HOST" && -n "$GITHUB_OWNER" && -n "$GITHUB_REPO" && -n "$GITHUB_ISSUE" ]] || usage

case "$ROLE" in
  worker1)
    :
    ;;
  worker2)
    :
    ;;
  *)
    echo "Sadece worker1 veya worker2 destekleniyor: $ROLE"
    exit 1
    ;;
esac

if [[ -z "$NODE_NAME" ]]; then
  if [[ "$ROLE" == "worker1" ]]; then
    NODE_NAME="Worker1"
  else
    NODE_NAME="Worker2"
  fi
fi

if [[ -z "$COORDINATOR_URL" ]]; then
  COORDINATOR_URL="http://${M5_HOST}:9000"
fi

ENV_FILE="$WORKDIR/.env.${ROLE}.local"

cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/join_mac_node.sh
export DERGAH_NODE_ROLE="worker"
export DERGAH_NODE_NAME="${NODE_NAME}"

export DERGAH_LLM_PROVIDER="${PROVIDER}"
export DERGAH_MODEL_NAME="${MODEL_NAME}"
export DERGAH_OPENAI_API_BASE="http://${M5_HOST}:52415/v1"
export DERGAH_OPENAI_API_KEY=""
export DERGAH_LLM_TIMEOUT="120"
export DERGAH_LLM_FALLBACK_OLLAMA="1"
export DERGAH_OLLAMA_FALLBACK_MODEL="qwen2.5-coder:14b"

export OPENCLAW_ROLE="worker"
export OPENCLAW_NODE_NAME="${NODE_NAME}"
export OPENCLAW_COORDINATOR_URL="${COORDINATOR_URL}"

export DERGAH_GITHUB_OWNER="${GITHUB_OWNER}"
export DERGAH_GITHUB_REPO="${GITHUB_REPO}"
export DERGAH_GITHUB_TOKEN="${GITHUB_TOKEN}"
export DERGAH_GITHUB_CHANNEL_ISSUE="${GITHUB_ISSUE}"
export DERGAH_GITHUB_API_BASE="https://api.github.com"
EOF

echo "Node env yazildi: ${ENV_FILE}"

if [[ "$START_STATUS" == "1" ]]; then
  "$WORKDIR/scripts/start_node.sh" "$ROLE" status
fi

if [[ "$START_RELAY" == "1" ]]; then
  "$WORKDIR/scripts/start_node.sh" "$ROLE" relay-listen
fi

if [[ "$START_OPENCLAW" == "1" ]]; then
  "$WORKDIR/scripts/start_node.sh" "$ROLE" openclaw
fi

echo "Sonraki adimlar:"
echo "1) source ${ENV_FILE}"
echo "2) scripts/start_node.sh ${ROLE} status"
echo "3) scripts/start_node.sh ${ROLE} relay-listen"
echo "4) scripts/start_node.sh ${ROLE} openclaw"
