org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true

# Application ID settings used by android/app/build.gradle.kts
# Keep defaults unless you have matching ABTO license + Firebase config.
inteliex.applicationId=com.sesdata.inteliex_softphone
inteliex.debugSuffix=.debug
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
